# Generated by Django 4.2.16 on 2026-03-24 08:20

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BureauEtudeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(default="Bureau d'Étude", max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, verbose_name='Adresse spécifique')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone spécifique')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email spécifique')),
                ('invoice_prefix', models.CharField(default='E', help_text='Utilisé dans les références — ex. E → E-2026-001.', max_length=10, verbose_name='Préfixe des factures')),
                ('proforma_prefix', models.CharField(default='FP-E', help_text='Utilisé dans les références proforma — ex. FP-E → FP-E-001-2026.', max_length=10, verbose_name='Préfixe proforma')),
                ('tva_applicable', models.BooleanField(default=True, verbose_name='TVA applicable')),
                ('tva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.19'), help_text='Taux standard 19% pour les études et le conseil.', max_digits=5, verbose_name='Taux de TVA')),
                ('rc', models.CharField(blank=True, max_length=100, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=100, verbose_name='NIS')),
                ('article_imposition', models.CharField(blank=True, max_length=100, verbose_name="Article d'imposition (ART.I)")),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Banque')),
                ('bank_account', models.CharField(blank=True, max_length=255, verbose_name='N° de compte')),
                ('bank_rib', models.CharField(blank=True, max_length=255, verbose_name='RIB')),
                ('chief_engineer_name', models.CharField(blank=True, max_length=255, verbose_name='Ingénieur en chef')),
                ('chief_engineer_title', models.CharField(blank=True, max_length=255, verbose_name='Titre')),
                ('chief_engineer_signature', models.ImageField(blank=True, upload_to='etudes/', verbose_name="Signature de l'ingénieur en chef")),
            ],
            options={
                'verbose_name': "Informations Bureau d'Étude",
                'verbose_name_plural': "Informations Bureau d'Étude",
            },
        ),
        migrations.CreateModel(
            name='FormationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(default='Centre de Formation', max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('address', models.TextField(blank=True, verbose_name='Adresse spécifique')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone spécifique')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email spécifique')),
                ('invoice_prefix', models.CharField(default='F', help_text='Utilisé dans les références — ex. F → F-2026-001.', max_length=10, verbose_name='Préfixe des factures')),
                ('proforma_prefix', models.CharField(default='FP', help_text='Utilisé dans les références proforma — ex. FP → FP-001-2026.', max_length=10, verbose_name='Préfixe proforma')),
                ('tva_applicable', models.BooleanField(default=True, verbose_name='TVA applicable')),
                ('tva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.09'), help_text='Taux réduit 9% pour les prestations de formation professionnelle.', max_digits=5, verbose_name='Taux de TVA')),
                ('rc', models.CharField(blank=True, max_length=100, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=100, verbose_name='NIS')),
                ('article_imposition', models.CharField(blank=True, max_length=100, verbose_name="Article d'imposition (ART.I)")),
                ('agrement_number', models.CharField(blank=True, help_text='Ex. AGR/FORM/2019/0042', max_length=100, verbose_name='N° Agrément formation')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Banque')),
                ('bank_account', models.CharField(blank=True, max_length=255, verbose_name='N° de compte')),
                ('bank_rib', models.CharField(blank=True, max_length=255, verbose_name='RIB')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Directeur')),
                ('director_title', models.CharField(blank=True, max_length=255, verbose_name='Titre')),
                ('director_signature', models.ImageField(blank=True, upload_to='formations/', verbose_name='Signature du directeur')),
                ('attestation_validity_years', models.PositiveIntegerField(default=5, verbose_name='Validité des attestations (années)')),
                ('min_attendance_percent', models.PositiveIntegerField(default=80, help_text="Seuil de présence en dessous duquel aucune attestation n'est délivrée.", verbose_name='Présence minimale requise (%)')),
            ],
            options={
                'verbose_name': 'Informations Centre de Formation',
                'verbose_name_plural': 'Informations Centre de Formation',
            },
        ),
        migrations.CreateModel(
            name='InstituteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=255, verbose_name="Nom de l'institut")),
                ('abbreviation', models.CharField(blank=True, max_length=50, verbose_name='Abréviation')),
                ('address', models.TextField(verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('rc', models.CharField(blank=True, max_length=100, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=100, verbose_name='NIS')),
                ('article_imposition', models.CharField(blank=True, max_length=100, verbose_name="Article d'imposition (ART.I)")),
                ('agrement_number', models.CharField(blank=True, help_text="Numéro d'agrément officiel de l'institut (ex. formation professionnelle).", max_length=100, verbose_name='N° Agrément')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Banque')),
                ('bank_account', models.CharField(blank=True, max_length=255, verbose_name='N° de compte')),
                ('bank_rib', models.CharField(blank=True, max_length=255, verbose_name='RIB')),
                ('logo', models.ImageField(blank=True, upload_to='institute/', verbose_name='Logo')),
                ('director_signature', models.ImageField(blank=True, upload_to='institute/', verbose_name='Signature du directeur')),
                ('director_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du directeur')),
                ('director_title', models.CharField(blank=True, max_length=255, verbose_name='Titre du directeur')),
                ('invoice_footer_text', models.TextField(blank=True, help_text='Texte affiché en bas de chaque facture (conditions de paiement, etc.).', verbose_name='Pied de page des factures')),
            ],
            options={
                'verbose_name': "Informations de l'institut",
                'verbose_name_plural': "Informations de l'institut",
            },
        ),
    ]
