# Generated by Django 6.0.2 on 2026-03-06 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="bank_rib",
            field=models.CharField(
                blank=True,
                help_text="Relevé d'Identité Bancaire spécifique au bureau d'étude.",
                max_length=255,
                verbose_name="RIB du bureau d'étude",
            ),
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="legal_infos",
            field=models.TextField(
                blank=True,
                help_text="RC, NIF, NIS, ART.I propres au bureau d'étude (si différents de l'institut). Affiché dans la section Émetteur des factures.",
                verbose_name="Informations légales spécifiques",
            ),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="bank_rib",
            field=models.CharField(
                blank=True,
                help_text="Relevé d'Identité Bancaire spécifique au centre de formation.",
                max_length=255,
                verbose_name="RIB du centre de formation",
            ),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="legal_infos",
            field=models.TextField(
                blank=True,
                help_text="RC, NIF, NIS, ART.I, N° Agrément propres au centre de formation. Affiché dans la section Émetteur des factures.",
                verbose_name="Informations légales spécifiques",
            ),
        ),
        migrations.AlterField(
            model_name="bureauetudeinfo",
            name="proforma_prefix",
            field=models.CharField(
                default="FP-E",
                help_text="Utilisé dans les références proforma — ex. FP-E → FP-E-001-2026.",
                max_length=10,
                verbose_name="Préfixe proforma",
            ),
        ),
        migrations.AlterField(
            model_name="formationinfo",
            name="proforma_prefix",
            field=models.CharField(
                default="FP",
                help_text="Utilisé dans les références proforma — ex. FP → FP-001-2026.",
                max_length=10,
                verbose_name="Préfixe proforma",
            ),
        ),
    ]
