# Generated by Django 6.0.2 on 2026-03-07 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_bureauetudeinfo_bank_rib_bureauetudeinfo_legal_infos_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bureauetudeinfo",
            name="legal_infos",
        ),
        migrations.RemoveField(
            model_name="formationinfo",
            name="legal_infos",
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="article_imposition",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Article d'imposition (ART.I)"
            ),
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="N° de compte"
            ),
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Banque"),
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="nif",
            field=models.CharField(blank=True, max_length=100, verbose_name="NIF"),
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="nis",
            field=models.CharField(blank=True, max_length=100, verbose_name="NIS"),
        ),
        migrations.AddField(
            model_name="bureauetudeinfo",
            name="rc",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro RC"
            ),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="agrement_number",
            field=models.CharField(
                blank=True,
                help_text="Ex. AGR/FORM/2019/0042",
                max_length=100,
                verbose_name="N° Agrément formation",
            ),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="article_imposition",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Article d'imposition (ART.I)"
            ),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="bank_account",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="N° de compte"
            ),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="bank_name",
            field=models.CharField(blank=True, max_length=255, verbose_name="Banque"),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="nif",
            field=models.CharField(blank=True, max_length=100, verbose_name="NIF"),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="nis",
            field=models.CharField(blank=True, max_length=100, verbose_name="NIS"),
        ),
        migrations.AddField(
            model_name="formationinfo",
            name="rc",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Numéro RC"
            ),
        ),
        migrations.AlterField(
            model_name="bureauetudeinfo",
            name="bank_rib",
            field=models.CharField(blank=True, max_length=255, verbose_name="RIB"),
        ),
        migrations.AlterField(
            model_name="formationinfo",
            name="bank_rib",
            field=models.CharField(blank=True, max_length=255, verbose_name="RIB"),
        ),
    ]
