# Generated by Django 6.0.2 on 2026-02-21 12:02

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference', models.CharField(help_text='Généré automatiquement (ex. AV-2026-001).', max_length=50, unique=True, verbose_name="Numéro d'avoir")),
                ('date', models.DateField(verbose_name='Date')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT (DA)')),
                ('tva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.19'), max_digits=5, verbose_name='Taux TVA')),
                ('amount_tva', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TVA (DA)')),
                ('amount_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC (DA)')),
                ('is_full_reversal', models.BooleanField(default=False, verbose_name='Annulation totale')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_direct_cost', models.BooleanField(default=True, help_text='Coût direct = imputable à un service. Indirect = frais généraux.', verbose_name='Coût direct')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(help_text='Ex. Exercice 2026, Q1 2026.', max_length=100, verbose_name='Nom')),
                ('period_type', models.CharField(choices=[('year', 'Exercice annuel'), ('quarter', 'Trimestre'), ('month', 'Mois'), ('custom', 'Période personnalisée')], default='year', max_length=10)),
                ('date_start', models.DateField(verbose_name='Début')),
                ('date_end', models.DateField(verbose_name='Fin')),
                ('is_closed', models.BooleanField(default=False, help_text='Une période clôturée ne devrait plus recevoir de nouvelles écritures.', verbose_name='Clôturé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Période financière',
                'verbose_name_plural': 'Périodes financières',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('invoice_type', models.CharField(choices=[('formation', 'Formation'), ('etude', 'Étude')], max_length=20, verbose_name='Type')),
                ('reference', models.CharField(help_text='Ex. F-2026-001 ou E-2026-001 — généré automatiquement.', max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('invoice_date', models.DateField(verbose_name='Date de facturation')),
                ('due_date', models.DateField(blank=True, help_text='Laissez vide pour paiement comptant.', null=True, verbose_name="Date d'échéance")),
                ('client_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Nom client (snapshot)')),
                ('client_address_snapshot', models.TextField(blank=True, verbose_name='Adresse client (snapshot)')),
                ('client_nif_snapshot', models.CharField(blank=True, max_length=100, verbose_name='NIF client (snapshot)')),
                ('client_nis_snapshot', models.CharField(blank=True, max_length=100, verbose_name='NIS client (snapshot)')),
                ('client_rc_snapshot', models.CharField(blank=True, max_length=100, verbose_name='RC client (snapshot)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant HT (DA)')),
                ('tva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.19'), max_digits=5, verbose_name='Taux TVA')),
                ('amount_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant TVA (DA)')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant TTC (DA)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant payé (DA)')),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Reste à payer (DA)')),
                ('status', models.CharField(choices=[('unpaid', 'Non payée'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('voided', 'Annulée'), ('credit_note', 'Avoir émis')], default='unpaid', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('footer_text', models.TextField(blank=True, verbose_name='Pied de page (personnalisé)')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-reference'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('description', models.CharField(max_length=500, verbose_name='Désignation')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, verbose_name='Quantité')),
                ('unit', models.CharField(blank=True, help_text='Ex. participant, jour, heure, forfait.', max_length=50, verbose_name='Unité')),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire HT (DA)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement.', max_digits=14, verbose_name='Total HT (DA)')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['invoice', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (DA)')),
                ('method', models.CharField(choices=[('cash', 'Espèces'), ('bank_transfer', 'Virement bancaire'), ('cheque', 'Chèque'), ('other', 'Autre')], default='bank_transfer', max_length=20, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('reversed', 'Annulé / retourné')], default='confirmed', max_length=20, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, help_text='Numéro de virement, numéro de chèque, etc.', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (DA)')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur / bénéficiaire')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('is_overhead', models.BooleanField(default=False, help_text="Cocher si la dépense n'est pas imputable à un service ou projet.", verbose_name='Frais généraux')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Justificatif')),
                ('receipt_missing', models.BooleanField(default=False, help_text="Cocher si le justificatif n'est pas encore disponible.", verbose_name='Justificatif manquant')),
                ('approval_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='approved', max_length=20, verbose_name="Statut d'approbation")),
                ('approval_notes', models.TextField(blank=True, verbose_name="Notes d'approbation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('allocated_to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='etudes.studyproject', verbose_name='Projet')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
    ]
