# Generated by Django 4.2.16 on 2026-03-24 08:20

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formations', '0001_initial'),
        ('clients', '0001_initial'),
        ('etudes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference', models.CharField(help_text='Généré automatiquement — ex. AV-2026-001.', max_length=50, unique=True, verbose_name='N° Avoir')),
                ('date', models.DateField(verbose_name='Date')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('amount_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant HT (DA)')),
                ('tva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.09'), max_digits=5, verbose_name='Taux TVA')),
                ('amount_tva', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TVA (DA)')),
                ('amount_ttc', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant TTC (DA)')),
                ('is_full_reversal', models.BooleanField(default=False, verbose_name='Annulation totale')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Avoir',
                'verbose_name_plural': 'Avoirs',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (DA)')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur / bénéficiaire')),
                ('payment_reference', models.CharField(blank=True, max_length=100, verbose_name='Référence de paiement')),
                ('is_overhead', models.BooleanField(default=False, help_text='Cocher si non imputable à un service ou projet.', verbose_name='Frais généraux')),
                ('receipt', models.FileField(blank=True, upload_to='receipts/%Y/%m/', verbose_name='Justificatif')),
                ('receipt_missing', models.BooleanField(default=False, verbose_name='Justificatif manquant')),
                ('approval_status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Refusée')], default='approved', max_length=10, verbose_name="Statut d'approbation")),
                ('approval_notes', models.TextField(blank=True, verbose_name="Notes d'approbation")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_direct_cost', models.BooleanField(default=True, help_text='Coût direct = imputable à un service ou projet. Indirect = frais généraux.', verbose_name='Coût direct')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'Catégorie de dépense',
                'verbose_name_plural': 'Catégories de dépenses',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(help_text='Ex. Exercice 2026.', max_length=100, verbose_name='Nom')),
                ('period_type', models.CharField(choices=[('year', 'Exercice annuel'), ('quarter', 'Trimestre'), ('month', 'Mois'), ('custom', 'Période personnalisée')], default='year', max_length=10)),
                ('date_start', models.DateField(verbose_name='Début')),
                ('date_end', models.DateField(verbose_name='Fin')),
                ('is_closed', models.BooleanField(default=False, help_text='Une période clôturée ne devrait plus recevoir de nouvelles écritures.', verbose_name='Clôturé')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Période financière',
                'verbose_name_plural': 'Périodes financières',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('invoice_type', models.CharField(choices=[('formation', 'Formation'), ('etude', 'Étude')], db_index=True, max_length=20, verbose_name='Type')),
                ('phase', models.CharField(choices=[('proforma', 'Facture Proforma'), ('finale', 'Facture Finale')], db_index=True, default='proforma', max_length=10, verbose_name='Phase')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée au client'), ('unpaid', 'Non payée'), ('partially_paid', 'Partiellement payée'), ('paid', 'Payée'), ('voided', 'Annulée'), ('credit_note', 'Avoir émis')], db_index=True, default='draft', max_length=20, verbose_name='Statut')),
                ('proforma_reference', models.CharField(help_text='Généré automatiquement à la création. Format : {prefix}-{NNN}-{YEAR}.', max_length=50, unique=True, verbose_name='N° Proforma')),
                ('reference', models.CharField(blank=True, help_text='Généré automatiquement à la finalisation — séquence indépendante.', max_length=50, null=True, unique=True, verbose_name='N° Facture finale')),
                ('page_ref', models.CharField(blank=True, help_text='Ex. GSCOM — affiché en haut à droite du document imprimé.', max_length=100, verbose_name='Réf. interne (en-tête)')),
                ('client_name_snapshot', models.CharField(blank=True, max_length=255, verbose_name='Nom client (snapshot)')),
                ('client_address_snapshot', models.TextField(blank=True, verbose_name='Adresse client (snapshot)')),
                ('client_type_snapshot', models.CharField(blank=True, max_length=20, verbose_name='Type client (snapshot)')),
                ('client_nif_snapshot', models.CharField(blank=True, max_length=100, verbose_name='NIF client (snapshot)')),
                ('client_nis_snapshot', models.CharField(blank=True, max_length=100, verbose_name='NIS client (snapshot)')),
                ('client_rc_snapshot', models.CharField(blank=True, max_length=100, verbose_name='RC client (snapshot)')),
                ('client_ai_snapshot', models.CharField(blank=True, max_length=100, verbose_name='ART.I client (snapshot)')),
                ('client_nin_snapshot', models.CharField(blank=True, max_length=20, verbose_name='NIN client (snapshot)')),
                ('client_rib_snapshot', models.CharField(blank=True, max_length=255, verbose_name='RIB client (snapshot)')),
                ('client_tin_snapshot', models.CharField(blank=True, max_length=50, verbose_name='TIN client (snapshot)')),
                ('invoice_date', models.DateField(help_text='Date de la proforma; conservée sur la finale.', verbose_name="Date d'émission")),
                ('validity_date', models.DateField(blank=True, help_text="Défaut : 30 jours après la date d'émission.", null=True, verbose_name='Date de validité (proforma)')),
                ('due_date', models.DateField(blank=True, help_text="Optionnel — si non renseignée, n'apparaît pas sur la facture imprimée.", null=True, verbose_name="Date d'échéance (finale)")),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de finalisation')),
                ('bon_commande_number', models.CharField(blank=True, help_text='Requis pour finaliser la facture.', max_length=100, verbose_name='N° Bon de Commande client')),
                ('bon_commande_date', models.DateField(blank=True, null=True, verbose_name='Date du BC')),
                ('bon_commande_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Optionnel — pour cross-check avec le montant de la facture.', max_digits=14, null=True, verbose_name='Montant BC (vérification)')),
                ('bon_commande_scan', models.FileField(blank=True, upload_to='bons_commande/%Y/%m/', verbose_name='Scan BC (optionnel)')),
                ('amount_ht', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant HT (DA)')),
                ('tva_rate', models.DecimalField(decimal_places=4, default=Decimal('0.09'), help_text='9% pour les formations ; 19% pour les études. 0 si client exonéré.', max_digits=5, verbose_name='Taux TVA')),
                ('amount_tva', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant TVA (DA)')),
                ('amount_ttc', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant TTC (DA)')),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Montant payé (DA)')),
                ('amount_remaining', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, verbose_name='Reste à payer (DA)')),
                ('amount_in_words', models.CharField(blank=True, help_text='Généré automatiquement lors de la finalisation.', max_length=500, verbose_name='Montant en lettres')),
                ('mode_reglement', models.CharField(blank=True, choices=[('espece', 'Espèces'), ('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('traite', 'Traite'), ('autre', 'Autre')], default='', help_text='Choisi à la finalisation. Espèces déclenche le calcul du timbre fiscal.', max_length=20, verbose_name='Mode de règlement')),
                ('notes', models.TextField(blank=True, verbose_name='Notes internes')),
                ('footer_text', models.TextField(blank=True, help_text='Conditions de paiement, RIB, etc. Écrase le pied de page par défaut.', verbose_name='Pied de page (personnalisé)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Client')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='formations.session', verbose_name='Session (traçabilité)')),
                ('study_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='etudes.studyproject', verbose_name="Projet d'étude (traçabilité)")),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-invoice_date', '-proforma_reference'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Montant (DA)')),
                ('method', models.CharField(choices=[('virement', 'Virement bancaire'), ('cheque', 'Chèque'), ('especes', 'Espèces'), ('autre', 'Autre')], default='virement', max_length=10, verbose_name='Mode de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente de confirmation'), ('confirmed', 'Confirmé'), ('reversed', 'Annulé / retourné')], default='confirmed', max_length=10, verbose_name='Statut')),
                ('reference', models.CharField(blank=True, help_text='N° virement, n° chèque, etc.', max_length=100, verbose_name='Référence')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('description', models.CharField(help_text="Titre de la formation ou du livrable d'étude.", max_length=500, verbose_name='Désignation')),
                ('pricing_mode', models.CharField(choices=[('per_person', 'Par personne'), ('per_day', 'Par jour'), ('per_person_per_day', 'Par personne × par jour'), ('forfait', 'Forfait')], default='per_person', max_length=20, verbose_name='Mode de tarification')),
                ('nb_persons', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Utilisé pour per_person et per_person_per_day.', max_digits=8, verbose_name='Nombre de personnes')),
                ('nb_days', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Utilisé pour per_day et per_person_per_day.', max_digits=8, verbose_name='Nombre de jours')),
                ('unit_price_ht', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Prix unitaire HT (DA)')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Remise (%)')),
                ('total_ht', models.DecimalField(decimal_places=2, help_text='Calculé automatiquement selon le mode de tarification.', max_digits=14, verbose_name='Total HT (DA)')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial.invoice', verbose_name='Facture')),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'ordering': ['invoice', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='financialperiod',
            constraint=models.CheckConstraint(check=models.Q(('date_end__gte', models.F('date_start'))), name='financial_period_end_after_start'),
        ),
        migrations.AddField(
            model_name='expense',
            name='allocated_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='etudes.studyproject', verbose_name='Projet'),
        ),
        migrations.AddField(
            model_name='expense',
            name='allocated_to_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='formations.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='financial.expensecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='financial.invoice', verbose_name="Facture d'origine"),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['phase', 'status'], name='financial_i_phase_f3ff89_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'phase', 'status'], name='financial_i_client__1cb790_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'invoice_date'], name='financial_i_invoice_1d4eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='financial_e_date_e5ec32_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['approval_status'], name='financial_e_approva_a9a0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='financial_e_categor_eba5b0_idx'),
        ),
    ]
