# Generated by Django 6.0.2 on 2026-02-21 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('etudes', '0001_initial'),
        ('financial', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='allocated_to_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='formations.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='financial.expensecategory', verbose_name='Catégorie'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='clients.client', verbose_name='Client'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='formations.session', verbose_name='Session'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='study_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='etudes.studyproject', verbose_name="Projet d'étude"),
        ),
        migrations.AddField(
            model_name='creditnote',
            name='original_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='financial.invoice', verbose_name="Facture d'origine"),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='financial.invoice', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='project_phase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='etudes.projectphase', verbose_name='Phase liée'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='formations.session', verbose_name='Session liée'),
        ),
        migrations.AddField(
            model_name='payment',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='financial.invoice', verbose_name='Facture'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['date'], name='financial_e_date_e5ec32_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['approval_status'], name='financial_e_approva_a9a0dd_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['category'], name='financial_e_categor_eba5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='financial_i_status_c36524_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['client', 'status'], name='financial_i_client__478cf0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_type', 'invoice_date'], name='financial_i_invoice_1d4eeb_idx'),
        ),
    ]
