# Generated by Django 6.0.3 on 2026-05-04 18:17

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etudes', '0001_initial'),
        ('financial', '0001_initial'),
        ('formations', '0002_trainer_monthly_rate_trainer_nif_trainer_rib_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeneficiaryType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('slug', models.SlugField(help_text='Identifiant machine (ex. formateur, hotel).', unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Libellé')),
                ('color', models.CharField(default='#6B7280', max_length=7, verbose_name='Couleur (hex)')),
                ('is_seeded', models.BooleanField(default=False, help_text='Les entrées système ne peuvent pas être supprimées.', verbose_name='Entrée système')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Type de bénéficiaire',
                'verbose_name_plural': 'Types de bénéficiaires',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='daily_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarif journalier (snapshot)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='fiscal_year',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, help_text="Rempli automatiquement d'après la date.", null=True, verbose_name='Exercice fiscal'),
        ),
        migrations.AddField(
            model_name='expense',
            name='g50_month',
            field=models.DateField(blank=True, help_text='Premier jour du mois de déclaration G50 (ex. 2026-01-01 pour janvier 2026).', null=True, verbose_name='Mois G50'),
        ),
        migrations.AddField(
            model_name='expense',
            name='gross_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Montant avant retenue IRG. Rempli automatiquement si IRG = 0.', max_digits=14, null=True, verbose_name='Montant brut (DA)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='irg_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculé automatiquement : montant brut × taux IRG.', max_digits=14, verbose_name='Montant IRG (DA)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='irg_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Retenue à la source (ex. 0.10 = 10%). Copié depuis le bénéficiaire.', max_digits=5, verbose_name='Taux IRG'),
        ),
        migrations.AddField(
            model_name='expense',
            name='linked_formation',
            field=models.ForeignKey(blank=True, help_text="Pour le mode 'Par formation' — couvre l'ensemble des sessions.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainer_expenses', to='formations.formation', verbose_name='Formation liée (forfait)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='monthly_rate_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Tarif mensuel (snapshot)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='quarter',
            field=models.PositiveSmallIntegerField(blank=True, help_text='1–4, calculé automatiquement.', null=True, verbose_name='Trimestre'),
        ),
        migrations.AddField(
            model_name='expense',
            name='trainer_payment_mode',
            field=models.CharField(blank=True, choices=[('per_formation', 'Par formation (forfait global)'), ('per_session', 'Par session'), ('direct', 'Paiement direct (sans lien)')], help_text='Renseigner uniquement pour les dépenses liées à un formateur.', max_length=20, null=True, verbose_name='Mode de paiement formateur'),
        ),
        migrations.AddField(
            model_name='expense',
            name='training_period_label',
            field=models.CharField(blank=True, help_text="Ex. '22-24/12/2023' — description libre de la période couverte.", max_length=100, verbose_name='Période de formation'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Montant effectivement payé = montant brut − IRG.', max_digits=14, verbose_name='Montant net (DA)'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(db_index=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='supplier',
            field=models.CharField(blank=True, help_text='Utilisez le champ Bénéficiaire de préférence.', max_length=255, verbose_name='Fournisseur libre'),
        ),
        migrations.CreateModel(
            name='Beneficiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='Nom / Raison sociale')),
                ('is_trainer', models.BooleanField(default=False, verbose_name='Est un formateur')),
                ('is_employee', models.BooleanField(default=False, help_text='True pour les formateurs internes ou le personnel administratif.', verbose_name='Est un employé (interne)')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('rib', models.CharField(blank=True, max_length=255, verbose_name='RIB')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Tarif journalier (DA)')),
                ('monthly_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, verbose_name='Tarif mensuel (DA)')),
                ('irg_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='0 pour aucune retenue; 0.10 pour prestataires externes (10%).', max_digits=5, verbose_name='Taux IRG par défaut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('trainer', models.OneToOneField(blank=True, help_text='Rempli automatiquement pour les formateurs.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='beneficiary', to='formations.trainer', verbose_name='Formateur lié')),
                ('beneficiary_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='beneficiaries', to='financial.beneficiarytype', verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Bénéficiaire',
                'verbose_name_plural': 'Bénéficiaires',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='beneficiary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financial.beneficiary', verbose_name='Bénéficiaire'),
        ),
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('account_type', models.CharField(choices=[('especes', 'Espèces'), ('bank', 'Virement bancaire'), ('ccp', 'CCP'), ('cib', 'CIB / Carte bancaire'), ('cheque', 'Chèque'), ('autre', 'Autre')], max_length=20, verbose_name='Type de compte')),
                ('label', models.CharField(blank=True, help_text='Ex. CPA Agence Sétif, CCP 12345-67.', max_length=255, verbose_name='Libellé')),
                ('account_number', models.CharField(blank=True, help_text='RIB, numéro CCP, code CIB, etc.', max_length=255, verbose_name='Numéro / Code')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Banque / Établissement')),
                ('is_default', models.BooleanField(default=False, help_text='Un seul compte par défaut par bénéficiaire.', verbose_name='Compte par défaut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('beneficiary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='financial.beneficiary', verbose_name='Bénéficiaire')),
            ],
            options={
                'verbose_name': 'Compte de paiement',
                'verbose_name_plural': 'Comptes de paiement',
                'ordering': ['-is_default', 'account_type', 'label'],
            },
        ),
        migrations.AddField(
            model_name='expense',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='financial.paymentaccount', verbose_name='Compte de paiement'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['fiscal_year', 'quarter'], name='financial_e_fiscal__30de84_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['beneficiary'], name='financial_e_benefic_e3e0e0_idx'),
        ),
    ]
