# Generated by Django 6.0.3 on 2026-05-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_beneficiarytype_expense_daily_rate_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='payment_date',
            field=models.DateField(blank=True, db_index=True, help_text='Date effective du virement / paiement.', null=True, verbose_name='Date de règlement'),
        ),
    ]
