# Generated by Django 6.0.3 on 2026-05-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_expense_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='g50_month',
            field=models.DateField(blank=True, db_index=True, help_text='Premier jour du mois de déclaration G50 (ex. 2026-01-01 pour janvier 2026). Période fiscale générale — non liée au formateur.', null=True, verbose_name='Mois G50'),
        ),
    ]
