# Generated by Django 6.0.3 on 2026-05-06 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_alter_expense_g50_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text="Coût total pour l'organisme = montant prestataire + IRG versé à l'État.", max_digits=14, verbose_name='Coût total (DA)'),
        ),
    ]
