# Generated by Django 6.0.3 on 2026-05-22 19:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_alter_expense_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='tva_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Calculé automatiquement : montant TTC × taux / (1 + taux). Représente la TVA récupérable / déductible sur cette dépense.', max_digits=14, verbose_name='Montant TVA (DA)'),
        ),
        migrations.AddField(
            model_name='expense',
            name='tva_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Taux TVA applicable sur cette dépense (ex. 0.09 = 9%, 0.19 = 19%). Laissez à 0 si exonéré ou inconnu.', max_digits=5, verbose_name='Taux TVA'),
        ),
    ]
