# Generated by Django 6.0.2 on 2026-02-28 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Ordre')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('blocked', 'Bloquée')], default='pending', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Date de début')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name="Date d'échéance")),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name="Date d'achèvement")),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Heures estimées')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Heures réelles')),
                ('deliverable', models.CharField(blank=True, max_length=255, verbose_name='Livrable attendu')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Phase de projet',
                'verbose_name_plural': 'Phases de projet',
                'ordering': ['project', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectDeliverable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('document', models.FileField(upload_to='deliverables/%Y/%m/', verbose_name='Fichier')),
                ('version', models.CharField(default='1.0', max_length=20, verbose_name='Version')),
                ('submitted_to', models.CharField(blank=True, max_length=255, verbose_name='Remis à')),
                ('submission_date', models.DateField(blank=True, null=True, verbose_name='Date de remise')),
                ('client_approved', models.BooleanField(help_text='Null = en attente de retour.', null=True, verbose_name='Approuvé par le client')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliverables', to='etudes.projectphase', verbose_name='Phase')),
            ],
            options={
                'verbose_name': 'Livrable',
                'verbose_name_plural': 'Livrables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('reference', models.CharField(blank=True, help_text='Référence courte pour usage interne (ex. ETU-2026-001).', max_length=50, verbose_name='Référence interne')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('project_type', models.CharField(blank=True, help_text='Ex. Audit SST, Diagnostic incendie, Étude de risques ATEX.', max_length=255, verbose_name='Type de mission')),
                ('site_address', models.TextField(blank=True, verbose_name="Adresse du site d'intervention")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin réelle')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Budget contractuel (DA)')),
                ('status', models.CharField(choices=[('in_progress', 'En cours'), ('completed', 'Terminé'), ('on_hold', 'En pause'), ('cancelled', 'Annulé')], default='in_progress', max_length=20, verbose_name='Statut')),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Normale'), ('high', 'Haute'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='Priorité')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='study_projects', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': "Projet d'étude",
                'verbose_name_plural': "Projets d'étude",
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='projectphase',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phases', to='etudes.studyproject', verbose_name='Projet'),
        ),
    ]
