# Generated by Django 6.0.2 on 2026-02-21 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('client_type', models.CharField(choices=[('company', 'Entreprise'), ('individual', 'Particulier')], default='company', max_length=20, verbose_name='Type de client')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du contact principal')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du contact')),
                ('registration_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro RC')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('nis', models.CharField(blank=True, max_length=100, verbose_name='NIS')),
                ('activity_sector', models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité")),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver plutôt que supprimer un client ayant un historique.', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Fonction')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, help_text='Un seul contact principal par client.', verbose_name='Contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contact client',
                'verbose_name_plural': 'Contacts clients',
                'ordering': ['-is_primary', 'last_name'],
            },
        ),
    ]
