# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('client_type', models.CharField(choices=[('particulier', 'Particulier'), ('auto_entrepreneur', 'Auto-Entrepreneur'), ('entreprise', 'Entreprise'), ('startup', 'Startup')], db_index=True, default='entreprise', max_length=20, verbose_name='Type de client')),
                ('name', models.CharField(help_text='Raison sociale pour une entreprise, Nom Prénom pour un particulier.', max_length=255, verbose_name='Nom / Raison sociale')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Site web')),
                ('activity_sector', models.CharField(blank=True, max_length=255, verbose_name="Secteur d'activité")),
                ('contact_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du contact principal')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone du contact')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du contact')),
                ('nin', models.CharField(blank=True, help_text="Numéro d'Identité Nationale — 18 chiffres (particulier).", max_length=20, verbose_name='NIN')),
                ('nif', models.CharField(blank=True, max_length=100, verbose_name='NIF')),
                ('article_imposition', models.CharField(blank=True, help_text="Numéro d'article d'imposition — AE, entreprise et startup.", max_length=100, verbose_name="Article d'imposition (ART.I)")),
                ('nis', models.CharField(blank=True, max_length=100, verbose_name='NIS')),
                ('rc', models.CharField(blank=True, help_text='Registre de Commerce — ex. 21B 0094443-19/00.', max_length=100, verbose_name='Numéro RC')),
                ('rib', models.CharField(blank=True, help_text="Relevé d'Identité Bancaire — optionnel, tous types.", max_length=255, verbose_name='RIB')),
                ('tin', models.CharField(blank=True, help_text='Tax Identification Number — optionnel, tous types.', max_length=50, verbose_name='TIN')),
                ('carte_auto_entrepreneur', models.CharField(blank=True, help_text="Numéro délivré par l'ANAE.", max_length=100, verbose_name='N° Carte Auto-Entrepreneur')),
                ('label_startup_number', models.CharField(blank=True, max_length=100, verbose_name='N° Label Startup')),
                ('label_startup_date', models.DateField(blank=True, null=True, verbose_name="Date d'obtention du label")),
                ('programme_accompagnement', models.CharField(blank=True, help_text='ANIE / NEXUS / … — optionnel.', max_length=255, verbose_name="Programme d'accompagnement")),
                ('is_tva_exempt', models.BooleanField(default=False, help_text='Automatiquement mis à True pour les particuliers et auto-entrepreneurs. Peut être ajusté manuellement pour des cas spéciaux.', verbose_name='Exonéré de TVA')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FormeJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(help_text='Ex. SARL, SPA, EURL, SNCI, GIE — sigle court.', max_length=50, unique=True, verbose_name='Forme juridique')),
                ('description', models.CharField(blank=True, help_text='Ex. Société par Actions.', max_length=255, verbose_name='Description complète')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer sans supprimer.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Forme juridique',
                'verbose_name_plural': 'Formes juridiques',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Fonction')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('is_primary', models.BooleanField(default=False, help_text='Un seul contact principal par client.', verbose_name='Contact principal')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Contact client',
                'verbose_name_plural': 'Contacts clients',
                'ordering': ['-is_primary', 'last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='forme_juridique',
            field=models.ForeignKey(blank=True, help_text='SARL / SPA / EURL / … — entreprise et startup. Laisser vide pour particulier / auto-entrepreneur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.formejuridique', verbose_name='Forme juridique'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['client_type'], name='clients_cli_client__1e0f73_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active', 'name'], name='clients_cli_is_acti_a6dad7_idx'),
        ),
    ]
