# Generated by Django 6.0.2 on 2026-03-07 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormeJuridique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(help_text='Ex. SARL, SPA, EURL, SNCI, GIE — sigle court.', max_length=50, unique=True, verbose_name='Forme juridique')),
                ('description', models.CharField(blank=True, help_text='Ex. Société par Actions.', max_length=255, verbose_name='Description complète')),
                ('is_active', models.BooleanField(default=True, help_text='Décochez pour masquer sans supprimer.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Forme juridique',
                'verbose_name_plural': 'Formes juridiques',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='client',
            name='forme_juridique',
            field=models.ForeignKey(blank=True, help_text='SARL / SPA / EURL / … — entreprise et startup. Laisser vide pour particulier / auto-entrepreneur.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='clients.formejuridique', verbose_name='Forme juridique'),
        ),
    ]
