# Generated by Django 6.0.3 on 2026-03-25 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('code', models.CharField(help_text='Code officiel de la branche professionnelle (ex. ACP, AGR, BTP).', max_length=10, unique=True, verbose_name='Code branche')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Catégorie')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('color', models.CharField(default='#3B82F6', help_text="Couleur d'affichage dans l'interface (ex. #3B82F6).", max_length=7, verbose_name='Couleur (hex)')),
            ],
            options={
                'verbose_name': 'Catégorie de formation',
                'verbose_name_plural': 'Catégories de formation',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Trainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('specialty', models.CharField(blank=True, max_length=255, verbose_name='Spécialité')),
                ('daily_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Tarif journalier (DA)')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('certifications', models.TextField(blank=True, verbose_name='Certifications et habilitations')),
                ('cv', models.FileField(blank=True, upload_to='trainers/cvs/', verbose_name='CV')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Formateur',
                'verbose_name_plural': 'Formateurs',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Capacité')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Emplacement')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Projecteur')),
                ('has_whiteboard', models.BooleanField(default=False, verbose_name='Tableau blanc')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Climatisation')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Salle de formation',
                'verbose_name_plural': 'Salles de formation',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('slug', models.SlugField(help_text='Identifiant URL-friendly (généré automatiquement).', max_length=255, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('objectives', models.TextField(blank=True, verbose_name='Objectifs pédagogiques')),
                ('target_audience', models.TextField(blank=True, verbose_name='Public cible')),
                ('prerequisites', models.TextField(blank=True, verbose_name='Prérequis')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Durée (jours)')),
                ('duration_hours', models.PositiveIntegerField(default=8, verbose_name='Durée (heures)')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Prix de base (DA)')),
                ('max_participants', models.PositiveIntegerField(default=20, verbose_name='Capacité maximale')),
                ('min_participants', models.PositiveIntegerField(default=5, verbose_name='Minimum de participants')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('accreditation_body', models.CharField(blank=True, max_length=255, verbose_name="Organisme d'accréditation")),
                ('accreditation_reference', models.CharField(blank=True, max_length=100, verbose_name="Référence d'accréditation")),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations', to='formations.formationcategory', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_start', models.DateField(verbose_name='Date de début')),
                ('date_end', models.DateField(verbose_name='Date de fin')),
                ('external_location', models.CharField(blank=True, max_length=255, verbose_name='Lieu externe (si hors-site)')),
                ('capacity', models.PositiveIntegerField(default=20, verbose_name='Capacité')),
                ('session_hours', models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures de cette session. Utilisé pour le calcul proportionnel du prix : prix_formation / durée_totale_h × durée_session_h.", max_digits=6, null=True, verbose_name='Durée de la session (heures)')),
                ('price_per_participant', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Prix par participant (DA)')),
                ('status', models.CharField(choices=[('planned', 'Planifiée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='planned', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Motif d'annulation")),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='clients.client', verbose_name='Client')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='formations.formation', verbose_name='Formation')),
                ('trainer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='formations.trainer', verbose_name='Formateur')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='formations.trainingroom', verbose_name='Salle')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['-date_start'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom')),
                ('employer', models.CharField(blank=True, max_length=255, verbose_name='Employeur')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('job_title', models.CharField(blank=True, max_length=255, verbose_name='Fonction')),
                ('attended', models.BooleanField(default=True, verbose_name='Présent')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('employer_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participants', to='clients.client', verbose_name='Employeur (client enregistré)')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='formations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Participant',
                'verbose_name_plural': 'Participants',
                'ordering': ['last_name', 'first_name'],
                'unique_together': {('session', 'first_name', 'last_name', 'email')},
            },
        ),
        migrations.CreateModel(
            name='Attestation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('reference', models.CharField(max_length=50, unique=True, verbose_name='Référence')),
                ('issue_date', models.DateField(verbose_name="Date d'émission")),
                ('valid_until', models.DateField(verbose_name="Valide jusqu'au")),
                ('is_issued', models.BooleanField(default=True, verbose_name='Émise')),
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='attestation', to='formations.participant', verbose_name='Participant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attestations', to='formations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': 'Attestation',
                'verbose_name_plural': 'Attestations',
                'ordering': ['-issue_date'],
            },
        ),
    ]
