# Generated by Django 6.0.3 on 2026-05-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='monthly_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Utilisé pour les formateurs internes ou les contrats au forfait mensuel.', max_digits=12, verbose_name='Tarif mensuel (DA)'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='nif',
            field=models.CharField(blank=True, max_length=100, verbose_name='NIF'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='rib',
            field=models.CharField(blank=True, help_text="Relevé d'Identité Bancaire — pour virement.", max_length=255, verbose_name='RIB'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='trainer_type',
            field=models.CharField(choices=[('internal', 'Interne (salarié)'), ('external', 'Externe (prestataire)')], db_index=True, default='external', max_length=10, verbose_name='Type'),
        ),
    ]
