# Generated by Django 6.0.2 on 2026-03-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_hours',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Nombre d'heures de cette session. Utilisé pour le calcul proportionnel du prix : prix_formation / durée_totale_h × durée_session_h.", max_digits=6, null=True, verbose_name='Durée de la session (heures)'),
        ),
    ]
