# Generated by Django 6.0.3 on 2026-03-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('etudes', '0001_initial'),
        ('formations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('name', models.CharField(max_length=255, verbose_name='Nom')),
                ('category', models.CharField(max_length=255, verbose_name='Catégorie')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de série')),
                ('model_number', models.CharField(blank=True, max_length=100, verbose_name='Référence modèle')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='Fournisseur')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='Fin de garantie')),
                ('purchase_date', models.DateField(verbose_name="Date d'achat")),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=12, verbose_name="Coût d'achat (DA)")),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valeur actuelle estimée (DA)')),
                ('useful_life_years', models.PositiveIntegerField(default=5, verbose_name='Durée de vie utile (années)')),
                ('condition', models.CharField(choices=[('good', 'Bon état'), ('needs_review', 'À réviser'), ('out_of_service', 'Hors service')], default='good', max_length=20, verbose_name='État')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('maintenance', 'En maintenance'), ('reserved', 'Mis en réserve'), ('for_sale', 'À vendre / Réformer')], default='active', max_length=20, verbose_name='Statut')),
                ('location', models.CharField(blank=True, max_length=255, verbose_name='Emplacement')),
                ('maintenance_interval_days', models.PositiveIntegerField(default=180, verbose_name='Intervalle de maintenance (jours)')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'Équipement',
                'verbose_name_plural': 'Équipements',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date_from', models.DateField(verbose_name='Du')),
                ('date_to', models.DateField(verbose_name='Au')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='resources.equipment', verbose_name='Équipement')),
                ('reserved_for_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to='etudes.studyproject', verbose_name='Projet')),
                ('reserved_for_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_bookings', to='formations.session', verbose_name='Session')),
            ],
            options={
                'verbose_name': "Réservation d'équipement",
                'verbose_name_plural': "Réservations d'équipements",
                'ordering': ['date_from'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('duration_hours', models.DecimalField(decimal_places=2, default=1, max_digits=6, verbose_name='Durée (heures)')),
                ('context', models.TextField(blank=True, verbose_name='Contexte / détails')),
                ('assigned_to_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usages', to='etudes.studyproject', verbose_name='Projet')),
                ('assigned_to_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_usages', to='formations.session', verbose_name='Session')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='resources.equipment', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': "Utilisation d'équipement",
                'verbose_name_plural': "Utilisations d'équipements",
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('date', models.DateField(verbose_name='Date')),
                ('maintenance_type', models.CharField(choices=[('preventive', 'Préventif'), ('corrective', 'Correctif')], max_length=20, verbose_name='Type')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Coût (DA)')),
                ('performed_by', models.CharField(blank=True, max_length=255, verbose_name='Effectué par')),
                ('description', models.TextField(verbose_name='Description des travaux')),
                ('resolution', models.TextField(blank=True, verbose_name='Résolution / résultat')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='Prochaine échéance')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='resources.equipment', verbose_name='Équipement')),
            ],
            options={
                'verbose_name': 'Maintenance',
                'verbose_name_plural': 'Maintenances',
                'ordering': ['-date'],
            },
        ),
    ]
